### ISSUE TITLE
Review drivers for the Steering Group and LocalGov Drupal

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/steering-group#3]
@aaronhirtenstein mentioned that it would be good to review the drivers at the next steering group meeting. Just adding this as an issue to remind us and keep track.

**Comment by aaronhirtenstein** [comment]
cheers, I've added it to the agenda for next time so we don't forget

**Comment by aaronhirtenstein** [comment]
this has been around since last November and is very out of date so gonna close it.
